[package]
name = "validate_vst3"
version = "0.1.0"
edition = "2021"
description = "Validate all rismidi plugins using the VST3 SDK"
publish = false

[build-dependencies]
cmake = "0.1.50"
color-eyre = "0.6.3"
toml = "0.8.19"

[dependencies]
color-eyre = "0.6.3"
